function C(id, text, tags = [], extra = {}) {
  return { id, text, tags, w: { a: 2, b: 2 }, ...extra }
}

export const starter = {
  pack: 'starter',
  version: 1,
  namespace: 'starter',
  slotOrder: [
    'subject',
    'body',
    'wardrobe',
    'pose',
    'setting',
    'lighting',
    'camera',
    'mood',
    'style',
    'extras',
  ],
  fragments: {
    hair: [
      'long dark hair',
      'short cropped hair',
      'auburn waves',
      'silver hair',
      'tight coils',
      'a wet undercut',
      'braided hair',
      'a sleek bun',
    ],
    skin: [
      'deep brown skin',
      'olive skin',
      'pale skin with freckles',
      'golden-tan skin',
      'cool undertone skin',
    ],
  },
  rules: [
    { ifTag: 'outdoor', forbidTags: ['indoor', 'studio'] },
    { ifTag: 'indoor', forbidTags: ['outdoor', 'landscape'] },
    { mutex: ['nude', 'clothed'] },
    { mutex: ['solo', 'couple'] },
  ],
  negatives: {
    default:
      'low quality, blurry, watermark, text, extra limbs, deformed hands, extra fingers, child, teen, underage',
    photo:
      'cartoon, anime, illustration, painting, 3d render, deformed, extra fingers, watermark, text, child, teen',
    illustration:
      'photograph, photorealistic, oversharpened, extra fingers, watermark, child, teen',
    anime:
      'photorealistic, western comic, extra fingers, watermark, child, teen, loli',
  },
  slots: {
    subject: [
      C('sub_woman', 'an adult woman with {hair}', ['solo', 'femme']),
      C('sub_man', 'an adult man with {hair}', ['solo', 'masc']),
      C('sub_woman_curvy', 'an adult woman, curvy, {skin}', ['solo', 'femme']),
      C('sub_man_beard', 'an adult man with a full beard, {skin}', ['solo', 'masc']),
      C('sub_woman_athletic', 'an adult woman, athletic build, {hair}', ['solo', 'femme']),
      C('sub_man_lean', 'an adult man, lean and tattooed', ['solo', 'masc']),
      C('sub_nb', 'an adult nonbinary person with {hair}', ['solo']),
      C('sub_woman_silver', 'an adult woman, silver-haired, lined face', ['solo', 'femme']),
      C('sub_man_long', 'an adult man with long hair and a soft face', ['solo', 'masc']),
      C('sub_couple_wm', 'an adult couple, a woman and a man', ['couple']),
      C('sub_couple_ww', 'two adult women, close together', ['couple', 'femme']),
      C('sub_couple_mm', 'two adult men, close together', ['couple', 'masc']),
      C('sub_woman_dark', 'an adult woman, {skin}, {hair}', ['solo', 'femme']),
      C('sub_man_dark', 'an adult man, {skin}, closely shaved', ['solo', 'masc']),
      C('sub_woman_freckled', 'an adult woman, heavily freckled, {hair}', ['solo', 'femme']),
      C('sub_androgynous', 'an adult androgynous person, sharp features', ['solo']),
      C('sub_woman_plus', 'an adult woman, plus-size, confident posture', ['solo', 'femme']),
      C('sub_man_broad', 'an adult man, broad-shouldered, {skin}', ['solo', 'masc']),
    ],
    body: [
      C('bod_soft', 'soft stomach, natural body'),
      C('bod_muscular', 'defined muscles, veined forearms'),
      C('bod_tattoos', 'dense tattoos across the chest and arms'),
      C('bod_scars', 'a faint scar along the collarbone'),
      C('bod_marks', 'stretch marks on the hips'),
      C('bod_hair', 'visible body hair'),
      C('bod_smooth', 'smooth bare skin'),
      C('bod_pierced', 'nipple and ear piercings'),
      C('bod_collarbone', 'sharp collarbones, long neck'),
      C('bod_hands', 'large hands, worn knuckles'),
      C('bod_waist', 'narrow waist, wide hips'),
      C('bod_shoulders', 'broad shoulders tapering to the waist'),
      C('bod_back', 'a strong back, shoulder blades catching light'),
      C('bod_freckle_body', 'freckles across the shoulders'),
      C('bod_sweat', 'a sheen of sweat on the skin'),
      C('bod_oil', 'skin oiled and reflective'),
      C('bod_goose', 'gooseflesh, nipples tight from cool air'),
      C('bod_bite', 'a faint bite mark on the shoulder'),
    ],
    wardrobe: [
      C('war_silk_robe', 'an open silk robe', ['clothed']),
      C('war_lingerie', 'sheer black lingerie', ['clothed']),
      C('war_white_shirt', 'an unbuttoned white shirt, nothing underneath', ['clothed']),
      C('war_suit', 'a rumpled tailored suit, jacket off', ['clothed']),
      C('war_knit', 'an oversized knit that slips off one shoulder', ['clothed']),
      C('war_leather', 'a leather harness over bare skin', ['clothed']),
      C('war_towel', 'a towel slung low on the hips', ['clothed']),
      C('war_stockings', 'thigh-high stockings and a garter', ['clothed']),
      C('war_jeans', 'unbuttoned jeans, no shirt', ['clothed']),
      C('war_dress', 'a backless evening dress, unzipped', ['clothed']),
      C('war_wetshirt', 'a soaked white t-shirt clinging to the body', ['clothed']),
      C('war_corset', 'a half-unlaced corset', ['clothed']),
      C('war_robe_none', 'nothing but a thin gold chain', ['nude']),
      C('war_nude', 'fully nude', ['nude']),
      C('war_sheet', 'tangled bedsheets covering almost nothing', ['nude']),
      C('war_jewelry', 'jewelry only — rings, a heavy necklace', ['nude']),
      C('war_boots', 'combat boots and otherwise nude', ['nude']),
      C('war_apron', 'only an apron, tied at the back', ['clothed']),
      C('war_kimono', 'a loosely tied silk kimono', ['clothed']),
      C('war_sports', 'a sports bra and low slacks', ['clothed']),
      C('war_lace', 'ivory lace bodysuit', ['clothed']),
      C('war_tie', 'a loosened tie, shirt open', ['clothed']),
      C('war_coat', 'a long coat worn open, nothing else', ['clothed']),
      C('war_fishnet', 'fishnet and leather straps', ['clothed']),
    ],
    pose: [
      C('pos_recline', 'reclining on one elbow, looking at the camera'),
      C('pos_shoulder', 'looking back over one shoulder'),
      C('pos_stand_34', 'standing in a three-quarter turn'),
      C('pos_sit_edge', 'sitting on the edge of a bed', [], { requires: ['indoor'] }),
      C('pos_against', 'pressed against a wall, one knee bent'),
      C('pos_arch', 'back arched, throat exposed'),
      C('pos_kneel', 'kneeling, hands resting on thighs'),
      C('pos_walk', 'walking toward the camera'),
      C('pos_stretch', 'stretching, arms overhead'),
      C('pos_mirror', 'caught in a mirror, mid-adjustment'),
      C('pos_hands_hair', 'hands in hair, eyes half-closed'),
      C('pos_profile', 'strict profile, chin slightly lifted'),
      C('pos_from_behind', 'seen from behind, head turned'),
      C('pos_lie_prone', 'lying prone, face turned to the side'),
      C('pos_straddle', 'straddling a chair, backwards', [], { requires: ['indoor'] }),
      C('pos_window', 'leaning on a windowsill', [], { requires: ['indoor'] }),
      C('pos_floor', 'sitting on the floor, knees drawn up'),
      C('pos_embrace', 'an intimate embrace', [], { requires: ['couple'] }),
      C('pos_forehead', 'foreheads touching', [], { requires: ['couple'] }),
      C('pos_hands_waist', 'hands at a waist from behind', [], { requires: ['couple'] }),
    ],
    setting: [
      C('set_loft', 'a sunlit loft apartment', ['indoor']),
      C('set_hotel', 'a dim hotel room with heavy curtains', ['indoor']),
      C('set_studio', 'a bare photography studio', ['indoor', 'studio']),
      C('set_library', 'a private library, leather chairs', ['indoor']),
      C('set_bath', 'a marble bathroom, fogged glass', ['indoor']),
      C('set_kitchen', 'a late-night kitchen, one lamp on', ['indoor']),
      C('set_greenhouse', 'a warm greenhouse, wet leaves', ['indoor']),
      C('set_warehouse', 'an empty warehouse, concrete and dust', ['indoor']),
      C('set_cabin', 'a wood cabin, fire going', ['indoor']),
      C('set_rooftop', 'a city rooftop at dusk', ['outdoor']),
      C('set_forest', 'a mossy forest clearing', ['outdoor', 'landscape']),
      C('set_beach', 'a private beach, low tide', ['outdoor', 'landscape']),
      C('set_street', 'a rain-soaked empty street', ['outdoor']),
      C('set_field', 'a dry grass field at golden hour', ['outdoor', 'landscape']),
      C('set_pool', 'the edge of a night-lit pool', ['outdoor']),
      C('set_car', 'the back seat of a parked car', ['indoor']),
      C('set_balcony', 'a narrow balcony over the city', ['outdoor']),
      C('set_atelier', 'a painter’s atelier, drop cloths', ['indoor']),
      C('set_train', 'a night train compartment', ['indoor']),
      C('set_dunes', 'wind-cut sand dunes', ['outdoor', 'landscape']),
      C('set_chapel', 'a deconsecrated chapel', ['indoor']),
      C('set_bar', 'an after-hours bar, stools up', ['indoor']),
    ],
    lighting: [
      C('lit_window', 'soft window light', ['indoor']),
      C('lit_candle', 'candlelight, warm and low', ['indoor']),
      C('lit_practical', 'a single practical lamp, deep shadows', ['indoor']),
      C('lit_studio_soft', 'studio softbox, wraparound key', ['indoor', 'studio']),
      C('lit_neon', 'neon spill, magenta and cyan', ['indoor']),
      C('lit_golden', 'golden hour sidelight', ['outdoor']),
      C('lit_overcast', 'flat overcast daylight', ['outdoor']),
      C('lit_moon', 'cool moonlight', ['outdoor']),
      C('lit_noon', 'hard noon sun, sharp shadows', ['outdoor']),
      C('lit_rim', 'strong rim light, face in shadow'),
      C('lit_vol', 'volumetric light through haze'),
      C('lit_chiaroscuro', 'chiaroscuro, one hard source'),
      C('lit_bounce', 'bounced fill, open shadows'),
      C('lit_projector', 'projector light, image broken across skin', ['indoor']),
      C('lit_fireplace', 'flickering fireplace light', ['indoor']),
      C('lit_fluorescent', 'sickly fluorescent overhead', ['indoor']),
      C('lit_magic', 'magic hour, pink-orange sky', ['outdoor']),
      C('lit_street', 'sodium streetlight', ['outdoor']),
      C('lit_under', 'underlighting, slightly unholy'),
      C('lit_split', 'split lighting across the face'),
    ],
    camera: [
      C('cam_85', '85mm portrait, shallow depth of field', ['photo']),
      C('cam_35', '35mm, environmental, subject in frame', ['photo']),
      C('cam_50', '50mm, eye level, honest perspective', ['photo']),
      C('cam_low', 'low angle, slightly heroic'),
      C('cam_high', 'high angle, looking down'),
      C('cam_close', 'tight close-up on the mouth and throat'),
      C('cam_full', 'full-body, generous negative space'),
      C('cam_detail', 'detail crop: hands, fabric, skin'),
      C('cam_over', 'over-the-shoulder framing'),
      C('cam_dutch', 'a slight dutch tilt'),
      C('cam_film', 'shot on 35mm film, visible grain', ['photo']),
      C('cam_medium', 'medium format, creamy falloff', ['photo']),
      C('cam_polaroid', 'instant film, white border, slight fade', ['photo']),
      C('cam_anamorphic', 'anamorphic, horizontal flare', ['photo']),
      C('cam_mirrorless', 'sharp modern digital, natural color', ['photo']),
      C('cam_cctv', 'security-camera distance, voyeur framing'),
      C('cam_macro', 'macro texture of skin and cloth'),
      C('cam_wide', 'wide lens, slight distortion at edges'),
    ],
    mood: [
      C('moo_tender', 'tender, unhurried'),
      C('moo_hungry', 'hungry, barely restrained'),
      C('moo_languid', 'languid, post-coital calm'),
      C('moo_defiant', 'defiant, a little amused'),
      C('moo_lonely', 'lonely, quietly charged'),
      C('moo_playful', 'playful, almost laughing'),
      C('moo_ritual', 'ritual, deliberate'),
      C('moo_dream', 'dreamlike, slightly unreal'),
      C('moo_dangerous', 'dangerous, a held breath'),
      C('moo_melancholy', 'melancholy, late hour'),
      C('moo_heat', 'heat-struck, slow-moving'),
      C('moo_cool', 'cool, appraising'),
      C('moo_worship', 'worshipful, attentive'),
      C('moo_messy', 'messy, clothes half-off in a hurry'),
      C('moo_still', 'still, almost a painting'),
      C('moo_feral', 'feral, unguarded'),
    ],
    style: [
      C('sty_editorial', 'high-fashion editorial', ['photo']),
      C('sty_helmut', 'helmut-newton-adjacent, hard flash, gloss', ['photo']),
      C('sty_mapple', 'mapplethorpe-like, classical nude, black and white', ['photo']),
      C('sty_film_still', 'cinematic still, motivated light', ['photo']),
      C('sty_polaroid_art', 'intimate polaroid, amateur-adjacent', ['photo']),
      C('sty_oil', 'oil painting, visible brushwork', ['illustration']),
      C('sty_charcoal', 'charcoal figure drawing', ['illustration']),
      C('sty_ukiyo', 'ukiyo-e woodblock, flat color', ['illustration']),
      C('sty_comic', 'mature western comic inks', ['illustration']),
      C('sty_render', 'tasteful 3d render, subsurface skin'),
      C('sty_noir', 'black-and-white noir', ['photo']),
      C('sty_kodachrome', 'kodachrome palette, slightly faded', ['photo']),
      C('sty_pastel', 'pastel illustration, soft edges', ['illustration']),
      C('sty_ink', 'ink wash, spare and wet', ['illustration']),
      C('sty_docu', 'documentary photography, unstyled', ['photo']),
      C('sty_baroque', 'baroque painting, rich dark ground', ['illustration']),
      C('sty_cyber', 'neon-soaked cyberpunk still', ['photo']),
      C('sty_renaissance', 'renaissance panel, drapery and flesh', ['illustration']),
    ],
    extras: [
      C('ex_skin_detail', 'visible pores, fine hair, real skin'),
      C('ex_fabric', 'fabric catching the light, detailed weave'),
      C('ex_bokeh', 'creamy bokeh, background gone'),
      C('ex_dust', 'dust motes in the beam'),
      C('ex_rain', 'rain on glass, city smear'),
      C('ex_smoke', 'a thin thread of cigarette smoke'),
      C('ex_steam', 'steam in the air'),
      C('ex_wine', 'a glass of red wine, half gone'),
      C('ex_book', 'an open book, spine broken'),
      C('ex_petals', 'scattered petals on the floor'),
      C('ex_vinyl', 'a record spinning, out of focus'),
      C('ex_mirror_fx', 'a second reflection in glass'),
      C('ex_hands_extra', 'hands in the foreground, out of focus'),
      C('ex_grain', 'heavy film grain'),
      C('ex_color', 'muted, slightly desaturated color'),
      C('ex_contrast', 'deep blacks, restrained highlights'),
      C('ex_wet', 'skin and hair wet'),
      C('ex_shadow_face', 'eyes in shadow, mouth in light'),
      C('ex_asym', 'slight asymmetry, a lived-in face'),
      C('ex_quiet', 'no text, no watermark, clean frame'),
    ],
  },
}

export function chipCount(pack) {
  return Object.values(pack.slots).reduce((n, a) => n + a.length, 0)
}
